vdk-kerberos-auth: enable authentication to work inside a running async event loop
This change adds _run_coroutine function to ensure proper execution of a
get_tgt coroutine, even if called within an already running event loop
in asyncio (which in principal is not allowed)

This is happening when the plugin is invoked within a jupyter notebook
which runs within a async event loop started by tornado server.
And this causes following errors:
```
Traceback (most recent call last):
File
"/opt/conda/lib/python3.7/site-packages/vdk/plugin/kerberos/minikerberos_authenticator.py",
line 90, in _kinit
    loop.run_until_complete(get_tgt())
File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 563, in
run_until_complete
    self._check_runnung()
File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 526, in
_check_runnung
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
```

The way the fix works is
- If the current event loop is running, the function now starts a new
thread to run the coroutine, ensuring that it runs to completion without
conflict with the existing loop.
- Otherwise it creates a new asyncio event loop in the current thread
and runs the couritine as before.