control-service: add additional logging to synchronizer task Why Currently, we are experiencing an issue with the Synchronizer task; it is overflowing the task queue.
```
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@55435baf[Running, pool size = 10, active threads = 10, queued tasks = 1999, completed tasks = 1174429]] did not accept task: com.vmware.taurus.service.deploy.DataJobsSynchronizer$$Lambda$2193/0x00007fe844d1c6d0@774553e9
```

What
Added an additional logging. Increased the Scheduler Lock
lockAtMostFor to 24h since the default is 10m which could be lead to
timeout of the task in some cases.