control-service: failed data job deployment fix (#114)
A few data jobs deployment failures troubleshooted, cause is
ERROR: restart transaction: TransactionRetryWithProtoRefreshError:
WriteTooOldError.
In all the cases of parallel or sequential deployment failures observed,
stacktrace indicates DeploymentMonitor.saveDataJobStatus() is causing
the transaction contention.

Atomic conditional latestJobDeploymentStatus update by data job name
introduced, in favour of two separate operations - of pre-selecting
the data job with the purpose to later persist object to update a single
property.

Testing Done: unit & integration tests

Signed-off-by: ikoleva <ikoleva@vmware.com>