vdk-heartbeat: null datetime conversion fix
We've noticed an occasional error occurs, applying the stack trace:
File "/opt/buildenv/lib/python3.7/site-packages/vdk/internal/heartbeat/
job_controller.py", line 383, in check_job_execution_finished
self._datetime_from_iso_format(str(e["end_time"])) for e in
execution_list
TypeError: '>' not supported between instances of 'NoneType' and
'datetime.datetime'

The error seems to reproduce in case execution end_time is not yet
populated, and `max()` is attempting to compare datetime with NoneType.
The fix includes filtering out any empty end_times, so that we rely on
statuses and end_times populated only.
A broader Exception is added for handling during datetime conversion,
like a preventive step.

Testing done: did retrieve the Execution API response, did reproduce
same TypeError error via local code snippet, then verified the newly
introduced fix applied is operational.

Signed-off-by: ikoleva <ikoleva@vmware.com>