vdk-impala: add udf hive2server user error classification (#2056)
what: added a new error to be classified as user exception in the
vdk-impala plugin

why: a use case came up where the following excerpt of an exception was
classified as platform error:

`File "/vdk/site-packages/impala/hiveserver2.py", line 1397, in fetch
    resp = self._rpc('FetchResults', req, False)
  File "/vdk/site-packages/impala/hiveserver2.py", line 1085, in _rpc
    err_if_rpc_not_ok(response)
File "/vdk/site-packages/impala/hiveserver2.py", line 781, in
err_if_rpc_not_ok
    raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: UDF ERROR: Decimal expression overflowed


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/vdk/site-packages/vdk/internal/builtin_plugins/run/data_job.py",
line 73, in run_step
    step_executed = step.runner_func(step, context.job_input)`

testing: added case to the unit test

Signed-off-by: mrMoZ1 <mzhivkov@vmware.com>