vdk-control-cli: Fix traceback shown for broken config.ini (#648)
Currently, if the config.ini file of a data job contains a special unicode
character, Versatile Data Kit prints the whole traceback, which may confuse
the user as to what is happening.

This change handles the exception and prints a message with more user-friendly
details as to what might be the possible cause for the error. The complete traceback
is printed only in debug mode.

Testing Done: Added a unit test, and tested locally by deploying a data job, whose config.ini
file contained a special unicode character. Verified that no traceback appears in the terminal.
The message shown was:
```
Error: ¯\_(ツ)_/¯

what: Cannot parse the Data Job configuration file.
why: Configuration file config.ini is probably corrupted. Error: File contains no section headers.
file: '/home/andy/Documents/test-jobs/my-second-job/config.ini', line: 1
'Œ; Supported format: https://docs.python.org/3/library/configparser.html#supported-ini-file-structure\n'
consequences: Cannot deploy and configure the data job without properly set config.ini file.
countermeasures: config.ini must be UTF-8 compliant. Make sure the file does not contain special Unicode characters, or that your text editor has not added such characters somewhere in the file.
```

Signed-off-by: Andon Andonov <andonova@vmware.com>