vdk-jupyter: cicd fix (#2780)
We had problems with the release: 
>       
> × Building wheel for y-py (pyproject.toml) did not run successfully.
>         │ exit code: 1
>         ╰─> [9 lines of output]
> Running `maturin pep517 build-wheel -i /usr/local/bin/python
--compatibility off`
>             🔗 Found pyo3 bindings
>             🐍 Found CPython 3.8 at /usr/local/bin/python
> error: package `y-py v0.6.2
(/tmp/pip-install-f40jsas6/y-py_d9865fc7363a49f684156a1cc9619ea2)`
cannot be built because it requires rustc 1.72 or newer, while the
currently active rustc version is 1.71.1

Updated the version of rustc adn added two additional dependencies.