control-service: add additional logging to synchronizer task (#3323)
Why
Currently, we are experiencing an issue with the Synchronizer task; it
is overflowing the task queue.

```
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@55435baf[Running, pool size = 10, active threads = 10, queued tasks = 1999, completed tasks = 1174429]] did not accept task: com.vmware.taurus.service.deploy.DataJobsSynchronizer$$Lambda$2193/0x00007fe844d1c6d0@774553e9
```

What
Added logging and increased the Scheduler Lock lockAtMostFor to 24h
since the default is 10m which could lead to timeout of the task in some
cases.

Signed-off by: Miroslav Ivanov
[miroslav.ivanov@broadcom.com](mailto:miroslav.ivanov@broadcom.com)

---------

Co-authored-by: github-actions <>