control-service: Update helm template license headers (#1670)
### What
Update helm template license headers to use template-style comments
Ignore helm templates in pre-commit yaml license hook Create new
pre-commit license hook to add template-style comments to helm templates

### Why
Regular yaml comments at the top of files break parsing for helm charts
This breaks control-service deployments

### How was this tested

Tested installing the charts on a local k8s cluster using helm

Ran `helm upgrade --install --debug --wait --timeout 10m0s
cicd-control-service .` on the chart, which gave me the same output as
the failing pipeline. Edited the comments until the apiVersion error
disappeared.

```
Error: UPGRADE FAILED: error validating "": error validating data: apiVersion not set
```

https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3813924321

Signed-off-by: Dilyan Marinov <mdilyan@vmware.com>